version: 2

jobs:
  install-and-test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install apt test dependencies
          command: |
              apt update
              apt install -y python3 python3-dev python3-wheel python3-pip
              apt install -y cmake g++ wget
      - run:
          name: Install pip test dependencies
          command: pip3 install pip pytest flake8 --upgrade
      - run:
          name: Install pybind11 (for testing generated C++ code)
          environment:
            - PYBIND11_VERSION: 2.4.3
          command: |
              mkdir build_pybind && cd build_pybind
              wget -nc --quiet https://github.com/pybind/pybind11/archive/v${PYBIND11_VERSION}.tar.gz
              tar -xf v${PYBIND11_VERSION}.tar.gz
              cd pybind11-${PYBIND11_VERSION} && mkdir build && cd build
              cmake -DPYBIND11_TEST=False ../
              make && make install
              cd ../../.. && rm -rf build_pybind
      - run:
          name: Install Raschii with its dependencies
          command: pip3 install .
      #- run:
      #    name: Flake8
      #    command: python3 -m flake8 raschii
      - run:
          name: Run unit tests
          command: python3 -m pytest -v tests/ --junitxml=~/reports/pytest/py3.xml --durations=10
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

workflows:
  version: 2
  on-commit:  # Runs on every commit
    jobs:
      - install-and-test
  scheduled:  # Runs every Saturday morning at 08:00 UTC
    triggers:
      - schedule:
          cron: "0 8 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - install-and-test
